apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-prod
  namespace: willcataco-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
