apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-prod
  namespace: willcataco-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-willcataco.chakisoft.com
    secretName: backend-api-tls-prod
  rules:
  - host: api-willcataco.chakisoft.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-prod
            port:
              number: 80
