apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-prod-frontend
  namespace: willcataco-prod
  labels:
    app: willcataco-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: prod
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: prod
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:prod-2ffd4ebd1870d4c396f8b7a9fbf23d455ed7f4c1
          ports:
            - containerPort: 80