apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: willcataco-prod-frontend
  namespace: willcataco-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - willcataco.chakisoft.com
      secretName: frontend-tls-prod
  rules:
    - host: willcataco.chakisoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: willcataco-prod-frontend
                port:
                  number: 80
