apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  namespace: willcataco-dev
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-821003b0db5a33ef752e404d7e9fb2d9e40d9947
          ports:
            - containerPort: 80
