apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  namespace: willcataco-dev
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-2e755bad81b17c02397015574aad11a556c5f341
          ports:
            - containerPort: 80
