apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: willcataco-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
      - name: backend
        image: ghcr.io/willcataco-los-papus-y-sebas/willcataco-server:dev-48136e48013688bb10d6c217f8a33ec3525c8b90
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets-dev
        env:
        - name: DB_HOST
          value: postgres-dev
        - name: DB_PORT
          value: "5432"
        - name: ENVIRONMENT
          value: development
