apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-dev
  namespace: willcataco-dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev-api-willcataco.chakisoft.com
    secretName: backend-api-tls-dev
  rules:
  - host: dev-api-willcataco.chakisoft.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-dev
            port:
              number: 80
